'use client'
import dynamic from "next/dynamic"

const Icons = {
  PlusIcon: dynamic(() => import("./plus.svg"), { ssr: false }),
  CloseIcon: dynamic(() => import("./close.svg"), { ssr: false }),
  BoxIcon: dynamic(() => import("./box.svg"), { ssr: false }),
  CheckCircleIcon: dynamic(() => import("./check-circle.svg"), { ssr: false }),
  AlertIcon: dynamic(() => import("./alert.svg"), { ssr: false }),
  InfoIcon: dynamic(() => import("./info.svg"), { ssr: false }),
  ErrorIcon: dynamic(() => import("./info-hexa.svg"), { ssr: false }),
  BoltIcon: dynamic(() => import("./bolt.svg"), { ssr: false }),
  ArrowUpIcon: dynamic(() => import("./arrow-up.svg"), { ssr: false }),
  ArrowDownIcon: dynamic(() => import("./arrow-down.svg"), { ssr: false }),
  FolderIcon: dynamic(() => import("./folder.svg"), { ssr: false }),
  VideoIcon: dynamic(() => import("./videos.svg"), { ssr: false }),
  AudioIcon: dynamic(() => import("./audio.svg"), { ssr: false }),
  GridIcon: dynamic(() => import("./grid.svg"), { ssr: false }),
  FileIcon: dynamic(() => import("./file.svg"), { ssr: false }),
  DownloadIcon: dynamic(() => import("./download.svg"), { ssr: false }),
  ArrowRightIcon: dynamic(() => import("./arrow-right.svg"), { ssr: false }),
  GroupIcon: dynamic(() => import("./group.svg"), { ssr: false }),
  BoxIconLine: dynamic(() => import("./box-line.svg"), { ssr: false }),
  ShootingStarIcon: dynamic(() => import("./shooting-star.svg"), { ssr: false }),
  DollarLineIcon: dynamic(() => import("./dollar-line.svg"), { ssr: false }),
  TrashBinIcon: dynamic(() => import("./trash.svg"), { ssr: false }),
  AngleUpIcon: dynamic(() => import("./angle-up.svg"), { ssr: false }),
  AngleDownIcon: dynamic(() => import("./angle-down.svg"), { ssr: false }),
  PencilIcon: dynamic(() => import("./pencil.svg"), { ssr: false }),
  CheckLineIcon: dynamic(() => import("./check-line.svg"), { ssr: false }),
  CloseLineIcon: dynamic(() => import("./close-line.svg"), { ssr: false }),
  ChevronDownIcon: dynamic(() => import("./chevron-down.svg"), { ssr: false }),
  ChevronUpIcon: dynamic(() => import("./chevron-up.svg"), { ssr: false }),
  PaperPlaneIcon: dynamic(() => import("./paper-plane.svg"), { ssr: false }),
  LockIcon: dynamic(() => import("./lock.svg"), { ssr: false }),
  EnvelopeIcon: dynamic(() => import("./envelope.svg"), { ssr: false }),
  UserIcon: dynamic(() => import("./user-line.svg"), { ssr: false }),
  CalenderIcon: dynamic(() => import("./calender-line.svg"), { ssr: false }),
  EyeIcon: dynamic(() => import("./eye.svg"), { ssr: false }),
  EyeCloseIcon: dynamic(() => import("./eye-close.svg"), { ssr: false }),
  TimeIcon: dynamic(() => import("./time.svg"), { ssr: false }),
  CopyIcon: dynamic(() => import("./copy.svg"), { ssr: false }),
  ChevronLeftIcon: dynamic(() => import("./chevron-left.svg"), { ssr: false }),
  UserCircleIcon: dynamic(() => import("./user-circle.svg"), { ssr: false }),
  TaskIcon: dynamic(() => import("./task-icon.svg"), { ssr: false }),
  ListIcon: dynamic(() => import("./list.svg"), { ssr: false }),
  TableIcon: dynamic(() => import("./table.svg"), { ssr: false }),
  PageIcon: dynamic(() => import("./page.svg"), { ssr: false }),
  PieChartIcon: dynamic(() => import("./pie-chart.svg"), { ssr: false }),
  BoxCubeIcon: dynamic(() => import("./box-cube.svg"), { ssr: false }),
  PlugInIcon: dynamic(() => import("./plug-in.svg"), { ssr: false }),
  DocsIcon: dynamic(() => import("./docs.svg"), { ssr: false }),
  MailIcon: dynamic(() => import("./mail-line.svg"), { ssr: false }),
  HorizontaLDots: dynamic(() => import("./horizontal-dots.svg"), { ssr: false }),
  ChatIcon: dynamic(() => import("./chat.svg"), { ssr: false }),
  MoreDotIcon: dynamic(() => import("./more-dot.svg"), { ssr: false }),
  BellIcon: dynamic(() => import("./bell.svg"), { ssr: false }),
}

export default function Icon({ name, className }) {
  const IconComponent = Icons[name]
  return IconComponent ? <span className={className}><IconComponent /></span> : <></>
  
}